#!/usr/bin/perl -CDS

#
# KanjiVG per-kanji test
# checks that stroke numbers exist and are consistent
# Copyright (C) 2012  Matthew Skala
#
# This program is dual licensed.  At your option, you may follow either of
# the two license notices below.
#
# Matthew Skala
# http://ansuz.sooke.bc.ca/
# mskala@ansuz.sooke.bc.ca
#
# GPL license:
#
#    This program is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by the
#    Free Software Foundation, either version 3 of the License, or (at your
#    option) any later version.
#
#    This program is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Creative Commons license:
#
#    This work is made available under the terms of the Creative Commons
#    Attribution-ShareAlike 3.0 license,
#    http://creativecommons.org/licenses/by-sa/3.0/.
#

########################################################################

$exit_code=0;
$max_stroke=0;

open(SVG,'kanji/'.shift.'.svg');
while (<SVG>) {
  if (/<path /) {
    $strokes++;
    if (/ kvg:strokenum="(.*?)"/) {
      $num=$1;
      if (($num==int($num)) && ($num>0)) {
        $count{$num}++;
        $max_stroke=$num if $num>$max_stroke;
      } else {
        print "Bad stroke number \"$num\"\n";
        $exit_code=1;
      }
    } else {
      print "Stroke without a number (sequential index $strokes)\n";
      $exit_code=1;
    }
  } elsif (/ kvg:strokenum="(.*?)"/) {
    print "Stroke number attribute other than in a path tag\n";
    $exit_code=1;
  }
}
close(SVG);

for ($i=1;$i<$max_stroke;$i++) {
  if ($count{$i}!=1) {
    print "There are $count{$i} strokes with number $i\n";
    $exit_code=1;
  }
}

exit $exit_code;
