#!/usr/bin/perl -CDS

#
# KanjiVG per-kanji test
# checks that the file can be parsed as XML and contains no unexpected tags
# Copyright (C) 2012  Matthew Skala
#
# This program is dual licensed.  At your option, you may follow either of
# the two license notices below.
#
# Matthew Skala
# http://ansuz.sooke.bc.ca/
# mskala@ansuz.sooke.bc.ca
#
# GPL license:
#
#    This program is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by the
#    Free Software Foundation, either version 3 of the License, or (at your
#    option) any later version.
#
#    This program is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Creative Commons license:
#
#    This work is made available under the terms of the Creative Commons
#    Attribution-ShareAlike 3.0 license,
#    http://creativecommons.org/licenses/by-sa/3.0/.
#

########################################################################


use XML::Parser;
use utf8;

$parser=new XML::Parser(Style=>'Subs');

$parser->setHandlers(Char=>\&ignore_char,Start=>\&check_tag);

$exit_code=0;

sub ignore_char { }
sub check_tag {
  my($expat,$element)=@_;
  
  if (!exists $known_tags{$element}) {
    print "unknown tag <$element>\n";
    $exit_code=1;
  }
}

%known_tags=(
  'g'=>1,
  'path'=>1,
  'svg'=>1,
  'text'=>1,
);

$/=undef;
open(SVG,'kanji/'.shift.'.svg');
$_=<SVG>;
close(SVG);
$db=$parser->parse($_);
# parse() calls die() if the parse fails, which is good enough for us

exit $exit_code;
